# Generated by Django 4.2.27 on 2025-12-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_menuitem_price_alter_order_discount_applied_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bank", "Chuyển Khoản Ngân Hàng"),
                    ("momo", "MoMo"),
                    ("cod", "Thanh Toán Khi Nhận Hàng"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
