# Generated by Django 4.2.27 on 2025-12-04 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_order_customer_name_order_delivery_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsfeed",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload video (MP4, MOV, AVI, or WebM format)",
                null=True,
                upload_to="news/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "avi", "webm"]
                    )
                ],
            ),
        ),
    ]
